### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by poldark1** [shijiebei2009/RedisDirectory#1]
我看到了代码中单例为坑的注释 那么我不用单例模式如何避免这个问题呢？

**Comment by shijiebei2009** [comment]
jedis同一时刻都是单例，这个注释是针对我的，不是用户的。


王旭   内容平台研发组/软件工程师
18302118258|291699763|021-61870500-9355
上海市浦东新区碧波路690号4层（201203）
www.yuewen.com

< poldark1> 2017-03-14 17:12:41 wrote: 
我看到了代码中单例为坑的注释 那么我不用单例模式如何避免这个问题呢？

**Comment by poldark1** [comment]
不好意思  我刚才的话说的有问题，我再修订一下。按我的理解是在应用与redis之间添加了lucence特性。目前也是这么做的。
现在有如下几个问题
1.首先使用为了避免加载过大，以及更新不及时。我采用的是多个模块多个dircetory和data 用传参替代了常量。但Lock_File_Path Lock file already exists!产生的异常不知有何影响。
2.对于查询机制的问题。在我创建IndexSearcher时是否将dircetory和data都进行了读取？这样在千万级数据是否会对应用造成压迫？如果提供查询服务，是否应将IndexSearcher作为单例对象使用？

**Comment by shijiebei2009** [comment]
@poldark1 这个项目是直接将lucene索引文件以二进制形式存入redis数据库。
1. 针对每个directory也就是索引目录，会有一把锁，这是为了防止多人同时写索引，请注意避免此类操作
2. 你是说你有多个writer，多个searcher，但是都存在同一份redis里面？在创建searcher并没有全部进行预读取，而是用到哪个索引文件就读取哪个索引文件，如果你数据量大建议先测试。分布式搜索的话可以使用SearcherManager进行管理，IndexSearcher最好是单例的。

**Comment by shijiebei2009** [comment]
@poldark1 
如果有多份索引同时写，那么每份索引都应该有一个自己独有的与他人不同的LOCK_FILE_PATH

**Comment by poldark1** [comment]
我现在根据商户信息 商品信息  交易信息等做成若干个directory和data，这几个directory有不同的更新时间。 在writer时用不同的key进行存储  后在应用根据3个不同的directory创建3个不同的IndexSearcher。按需获取。

**Comment by poldark1** [comment]
你是说你有多个writer，多个searcher，但是都存在同一份redis里面

是保存在同一个redis里。
存在多个不同类别的不同索引的searcher  但是writer我会委托给定时器操作。不会存在多个writer。

**Comment by poldark1** [comment]
那么如果是一个集群应用 那么针对writer LOCK_FILE_PATH是不是就失效了

**Comment by shijiebei2009** [comment]
一份索引，一个LOCK_FILE_PATH，不管你是什么，这个LOCK_FILE_PATH都能锁住这一份索引。

**Comment by poldark1** [comment]
我的意思是读写分离。应用会做集群。按照 声明IndexSearcher或者IndexWriter 都会执行ensureOpen操作，但我可能应用1使用(IndexWriter)  在应用1 应用2 应用3里使用IndexSearcher

**Comment by poldark1** [comment]
如果应用A 创建了索引文件完成  同时应用B用相同的配置创建，是覆盖的关系吗？

**Comment by poldark1** [comment]
一份索引，一个LOCK_FILE_PATH，不管你是什么，这个LOCK_FILE_PATH都能锁住这一份索引。

一份索引  多台机器的多个LOCK_FILE_PATH 会造成什么样的 影响

**Comment by shijiebei2009** [comment]
@poldark1 多台机器上的LOCK_FILE_PATH ，只要路径不同，不影响。

已经运行成功了吗？锁不存在肯定不影响，只是无法防止多人写而已，如果你能保证一人写，可以不用加锁的。

**Comment by poldark1** [comment]
redis里没有索引都无法建立起IndexSearcher啊。。。

**Comment by shijiebei2009** [comment]
@poldark1 lucene本身也不支持你没索引就建searcher啊
