### ISSUE TITLE
Run Hibernate Search on Redis Directory

### ISSUE THREAD

**Issue by gigincg** [shijiebei2009/RedisDirectory#2]
I'm trying to deploy hibernate search with the index in Redis. Since Hibernate Search uses a Directory based Lucene Index, I'm intrigued to know if RedisDirectory could possibly help attain this. 

Any pointers are appreciated.

Thanks in Advance!

**Comment by shijiebei2009** [comment]
@gigincg sorry, I'm not sure, you can have a try.
